name: tasks_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.15.0
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
