name: local_storage_tasks_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  sqflite: ^2.4.1
  path: ^1.9.0
  rxdart: ^0.28.0
  path_provider: ^2.1.5
  share_plus: ^10.1.3
  tasks_api:
    path: ../tasks_api


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
